create table if not exists public.reports (
  id text primary key,
  client_id text unique,
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  category text not null check (category in ('road_damage', 'landslide', 'flood', 'bridge_damage', 'blockage', 'traffic', 'other')),
  note text not null default '',
  photo_base64 text,
  device_id text,
  ts bigint not null
);

create index if not exists reports_ts_idx on public.reports (ts desc);

create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  device_id text not null,
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  ts bigint not null
);

create index if not exists positions_device_ts_idx on public.positions (device_id, ts asc);

-- The Node backend uses the service-role key, so these tables can remain
-- inaccessible to the browser. Enable RLS as a defense-in-depth measure.
alter table public.reports enable row level security;
alter table public.positions enable row level security;

create table if not exists public.missions (
  id text primary key,
  cargo_type text not null,
  cargo_quantity text,
  priority text not null default 'standard' check (priority in ('emergency', 'high', 'standard')),
  origin text not null,
  destination text not null,
  vehicle_id text,
  status text not null default 'planned' check (status in ('planned', 'in_transit', 'delayed', 'delivered', 'cancelled')),
  planned_eta bigint,
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists missions_status_idx on public.missions (status, updated_at desc);

create table if not exists public.delivery_stops (
  id text primary key,
  mission_id text not null references public.missions(id) on delete cascade,
  sequence integer not null,
  name text not null,
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  status text not null default 'pending' check (status in ('pending', 'arrived', 'completed', 'skipped')),
  eta bigint,
  arrived_at bigint
);

create index if not exists delivery_stops_mission_idx on public.delivery_stops (mission_id, sequence);

alter table public.missions enable row level security;
alter table public.delivery_stops enable row level security;
